name: Publish Crates to crates.io

on:
  workflow_dispatch:

# Publishes ic-btc-interface and ic-btc-validation to crates.io
# Run this after merging the release PR created by release-plz

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write # Required for OIDC token exchange

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate with crates.io
        id: auth
        uses: rust-lang/crates-io-auth-action@v1

      - name: Publish crates (release-plz)
        uses: release-plz/action@5ab144c9d67d4346240190d0f95ed08668677928 # v0.5.121
        with:
          command: release
          version: 0.3.151
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
