[package]
name = "scenario-3"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.28.1"
candid = { workspace = true }
ic-btc-test-utils = { path = "../../test-utils" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true}
serde = "1.0.132"
