[package]
name = "scenario-2"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.28.1"
candid = "0.7.4"
ic-btc-test-utils = { path = "../../../../ic/rs/bitcoin/test-utils" }
ic-cdk = "0.5.6"
ic-cdk-macros = "0.5.6"
serde = "1.0.132"
